const currencies = [
    { code: 'AUD', name: 'Australian Dollar', flag: 'node_modules/currency-flags/dist/square-flags/aud.svg' },
    { code: 'USD', name: 'United States Dollar', flag: 'node_modules/currency-flags/dist/square-flags/usd.svg' },
    { code: 'EUR', name: 'Euro', flag: 'node_modules/currency-flags/dist/square-flags/eur.svg' },
    { code: 'RUB', name: 'Russian Ruble', flag: 'node_modules/currency-flags/dist/square-flags/rub.svg' },
    { code: 'GBP', name: 'British Pound Sterling', flag: 'node_modules/currency-flags/dist/square-flags/gbp.svg' },
    { code: 'JPY', name: 'Japanese Yen', flag: 'node_modules/currency-flags/dist/square-flags/jpy.svg' },
    { code: 'CAD', name: 'Canadian Dollar', flag: 'node_modules/currency-flags/dist/square-flags/cad.svg' },
    { code: 'CHF', name: 'Swiss Franc', flag: 'node_modules/currency-flags/dist/square-flags/chf.svg' },
    { code: 'CNY', name: 'Chinese Yuan', flag: 'node_modules/currency-flags/dist/square-flags/cny.svg' },
    { code: 'SEK', name: 'Swedish Krona', flag: 'node_modules/currency-flags/dist/square-flags/sek.svg' },
    { code: 'NZD', name: 'New Zealand Dollar', flag: 'node_modules/currency-flags/dist/square-flags/nzd.svg' },
    { code: 'KRW', name: 'South Korean Won', flag: 'node_modules/currency-flags/dist/square-flags/krw.svg' },
    { code: 'SGD', name: 'Singapore Dollar', flag: 'node_modules/currency-flags/dist/square-flags/sgd.svg' },
    { code: 'NOK', name: 'Norwegian Krone', flag: 'node_modules/currency-flags/dist/square-flags/nok.svg' },
    { code: 'MXN', name: 'Mexican Peso', flag: 'node_modules/currency-flags/dist/square-flags/mxn.svg' },
    { code: 'INR', name: 'Indian Rupee', flag: 'node_modules/currency-flags/dist/square-flags/inr.svg' },
    { code: 'BRL', name: 'Brazilian Real', flag: 'node_modules/currency-flags/dist/square-flags/brl.svg' },
    { code: 'ZAR', name: 'South African Rand', flag: 'node_modules/currency-flags/dist/square-flags/zar.svg' },
    { code: 'TRY', name: 'Turkish Lira', flag: 'node_modules/currency-flags/dist/square-flags/try.svg' },
    { code: 'HKD', name: 'Hong Kong Dollar', flag: 'node_modules/currency-flags/dist/square-flags/hkd.svg' },
    { code: 'IDR', name: 'Indonesian Rupiah', flag: 'node_modules/currency-flags/dist/square-flags/idr.svg' },
    { code: 'PHP', name: 'Philippine Peso', flag: 'node_modules/currency-flags/dist/square-flags/php.svg' },
    { code: 'THB', name: 'Thai Baht', flag: 'node_modules/currency-flags/dist/square-flags/thb.svg' },
    { code: 'PLN', name: 'Polish Zloty', flag: 'node_modules/currency-flags/dist/square-flags/pln.svg' },
    { code: 'ILS', name: 'Israeli Shekel', flag: 'node_modules/currency-flags/dist/square-flags/ils.svg' },
    { code: 'CZK', name: 'Czech Koruna', flag: 'node_modules/currency-flags/dist/square-flags/czk.svg' },
    { code: 'CLP', name: 'Chilean Peso', flag: 'node_modules/currency-flags/dist/square-flags/clp.svg' },
    { code: 'AED', name: 'United Arab Emirates Dirham', flag: 'node_modules/currency-flags/dist/square-flags/aed.svg' },
    { code: 'SAR', name: 'Saudi Riyal', flag: 'node_modules/currency-flags/dist/square-flags/sar.svg' },
    { code: 'MYR', name: 'Malaysian Ringgit', flag: 'node_modules/currency-flags/dist/square-flags/myr.svg' },
    { code: 'COP', name: 'Colombian Peso', flag: 'node_modules/currency-flags/dist/square-flags/cop.svg' },
];

export default currencies;
